on:
  push:
    branches:
    - 'sc_jfrog'

name: "Assettoken contract push to Jfrog"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GITHUB_PAT_TOKEN }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - run: |    
          npm install
          npm run compile

      - uses: jfrog/setup-jfrog-cli@v1
        with:
          version: 1.35.1
        name: Jfrog CLI to push image and build info 
        env:
            JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      - run: |
            # push to the Jfrog with Build info
            TAG=`git log -1 --pretty=%h`
            jfrog rt u "build/contracts/AssetToken.json" QA_smart_contract/AssetToken/${TAG}/
            jfrog rt bp